CREATE TABLE bots (
    player_id BIGINT UNSIGNED NOT NULL,
    ckey VARCHAR(255) PRIMARY KEY,
    mode INT NOT NULL,
    url VARCHAR(500) NOT NULL,
    move_strategy VARCHAR(50) NOT NULL,
    cast_strategy VARCHAR(50) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_player FOREIGN KEY (player_id) REFERENCES players(id) ON DELETE CASCADE
);
