CREATE TABLE bots (
    ckey VARCHAR(255) NOT NULL,
    player_id INT NOT NULL,
    mode INT NOT NULL,
    move_strategy VARCHAR(50) NOT NULL,
    cast_strategy VARCHAR(50) NOT NULL,
    status VARCHAR(255) NOT NULL DEFAULT 'stopped',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (ckey)
);
